---
# tasks file for install_oracle

#Get OS Information.

- debug: 
    msg: "OS Family: {{ ansible_distribution }}"

#Install, configure AWS prerequisite.

- include: configure_aws_cfn.yml
  become: yes

#Install oracle when RedHat OS.

- include: install_oracle_rhel.yml
  become: yes
  when: ansible_distribution == 'RedHat'
