---
# tasks file for install_oracle

- debug:                               #Get OS information.
    msg: "OS Family: {{ ansible_distribution }}"

- include: install_oracle_rhel.yml           #Install oracle when RedHat OS.
  become: yes
  when: ansible_distribution == 'RedHat'